### ISSUE TITLE
Add ExPlat (A/B testing) support to Tracks

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS-Shared#278]
The goal is to add support to the ExPlat (A/B testing platform)

### Tasks

* [x] Request `wpcom/v2/experiments/0.1.0/assignments/<platform>` and store the experiments values (https://github.com/wordpress-mobile/WordPress-iOS/pull/15211)
* [ ] Request the above again when the ttl has been reached (take into account closing/reopening the app)
* [ ] Add anonymous support
* [ ] TBD: Privacy

**Comment by leandroalonso** [comment]
@aaronyan @astralbodies question regarding Privacy: some users opt-out to all the tracking we do. In this case, I'd personally not even perform this request. Does that sound reasonable for you two?

**Comment by aaronyan** [comment]
I think that sounds reasonable to not request an experiment assignment for users that opt-out. I don't think this introduces any bias into the experiment, but I'll think about it. Is the no request strategy how Tracks events are handled for users that opt-out?

**Comment by leandroalonso** [comment]
@aaronyan I just checked here and, yes, if the user opt-out we don't perform the Tracks request. (@astralbodies please correct me if I'm wrong).
